{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "boot-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "boot-chart.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "boot-chart.labels" . | nindent 6 }}

  {{/* Default to the release namespace if none provided */}}
  {{- $nsSel := (default (dict) .Values.metrics.serviceMonitor.namespaceSelector) -}}
  {{- $match := (default (list .Release.Namespace) (index $nsSel "matchNames")) -}}
  namespaceSelector:
    matchNames:
      {{- toYaml $match | nindent 6 }}

  endpoints:
    - port: {{ .Values.service.portName }}
      path: {{ .Values.metrics.path }}
      scheme: {{ .Values.metrics.scheme | default "HTTP" }}
      interval: {{ .Values.metrics.serviceMonitor.interval | default "15s" }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | default "10s" }}
{{- end }}
