{{- /*
  templates/servicemonitor.yaml
  Renders a ServiceMonitor using safe defaults and Helm values.
*/ -}}
{{- $metrics := .Values.metrics | default dict -}}
{{- $sm := $metrics.serviceMonitor | default dict -}}
{{- if and ($metrics.enabled | default false) ($sm.enabled | default false) }}

{{- /* Validate & normalize scheme */ -}}
{{- $scheme := (default "http" $metrics.scheme) | lower -}}
{{- if not (or (eq $scheme "http") (eq $scheme "https")) -}}
{{- fail (printf "metrics.scheme must be 'http' or 'https', got %q" $scheme) -}}
{{- end -}}

{{- /* Namespace selector (default to release namespace) */ -}}
{{- $nsSel := (default (dict) $sm.namespaceSelector) -}}
{{- $match := (default (list .Release.Namespace) (index $nsSel "matchNames")) -}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "boot-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "boot-chart.labels" . | nindent 4 }}
    {{- with $sm.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "boot-chart.labels" . | nindent 6 }}

  namespaceSelector:
    matchNames:
      {{- toYaml $match | nindent 6 }}

  endpoints:
    - port: {{ default "http" .Values.service.portName }}
      path: {{ default "/actuator/prometheus" $metrics.path }}
      scheme: {{ $scheme }}
      interval: {{ default "15s" $sm.interval }}
      scrapeTimeout: {{ default "10s" $sm.scrapeTimeout }}
      honorLabels: {{ default false $sm.honorLabels }}
      {{- with $sm.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $sm.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
